In [1]:
# import libraries
import boto3, re, sys, math, json, os, sagemaker, urllib.request
from sagemaker import get_execution_role
import numpy as np                                
import pandas as pd                               
import matplotlib.pyplot as plt                   
from IPython.display import Image                 
from IPython.display import display               
from time import gmtime, strftime                 
from sagemaker.predictor import csv_serializer   

# Define IAM role
role = get_execution_role()
prefix = 'sagemaker/DEMO-xgboost-dm'
containers = {'us-west-2': '433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest',
              'us-east-1': '811284229777.dkr.ecr.us-east-1.amazonaws.com/xgboost:latest',
              'us-east-2': '825641698319.dkr.ecr.us-east-2.amazonaws.com/xgboost:latest',
              'eu-west-1': '685385470294.dkr.ecr.eu-west-1.amazonaws.com/xgboost:latest'} # each region has its XGBoost container
my_region = boto3.session.Session().region_name # set the region of the instance
print("Success - the MySageMakerInstance is in the " + my_region + " region. You will use the " + containers[my_region] + " container for your SageMaker endpoint.")

Success - the MySageMakerInstance is in the us-east-1 region. You will use the 811284229777.dkr.ecr.us-east-1.amazonaws.com/xgboost:latest container for your SageMaker endpoint.


In [4]:
bucket_name = 'pa5-part2' # <--- change this variable to a unique name for your bucket
s3 = boto3.resource('s3')
try:
    if  my_region == 'us-east-1':
      s3.create_bucket(Bucket=bucket_name)
    else: 
      s3.create_bucket(Bucket=bucket_name, CreateBucketConfiguration={ 'LocationConstraint': my_region })
    print('S3 bucket created successfully')
except Exception as e:
    print('S3 error: ',e)

S3 bucket created successfully


In [5]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls


--2019-04-11 02:03:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/00350/default%20of%20credit%20card%20clients.xls
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5539328 (5.3M) [application/x-httpd-php]
Saving to: ‘default of credit card clients.xls’

default of credit c 100%[===================>]   5.28M  7.35MB/s    in 0.7s    

2019-04-11 02:03:08 (7.35 MB/s) - ‘default of credit card clients.xls’ saved [5539328/5539328]



In [6]:
dataset = pd.read_excel('default of credit card clients.xls')
pd.set_option('display.max_rows', 8)
pd.set_option('display.max_columns', 15)
dataset

X1   X2         X3        X4   X5     X6     X7  \
ID     LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2   
1          20000    2          2         1   24      2      2   
2         120000    2          2         2   26     -1      2   
3          90000    2          2         2   34      0      0   
...          ...  ...        ...       ...  ...    ...    ...   
29997     150000    1          3         2   43     -1     -1   
29998      30000    1          2         2   37      4      3   
29999      80000    1          3         1   41      1     -1   
30000      50000    1          2         1   46      0      0   

                  ...                   X18       X19       X20       X21  \
ID                ...              PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4   
1                 ...                     0       689         0         0   
2                 ...                     0      1000      1000      1000   
3                 ...                  1518      1500      1000      1000   
...               ...                   ...       ...       ...       ...   
29997             ...                  1837      3526      8998       129   
29998             ...                     0         0     22000      4200   
29999             ...                 85900      3409      1178      1926   
30000             ...                  2078      1800      1430      1000   

            X22       X23                           Y  
ID     PAY_AMT5  PAY_AMT6  default payment next month  
1             0         0                           1  
2             0      2000                           1  
3          1000      5000                           0  
...         ...       ...                         ...  
29997         0         0                           0  
29998      2000      3100                           1  
29999     52964      1804                           1  
30000      1000      1000                           1  

[30001 rows x 24 columns]

In [8]:
dataset = dataset.drop('ID')
dataset = pd.concat([dataset['Y'], dataset.drop(['Y'], axis=1)], axis=1) 

In [9]:
train_data, validation_data, test_data = np.split(dataset.sample(frac=1, random_state=1729), [int(0.7 * len(dataset)), int(0.9 * len(dataset))])
train_data.to_csv('train.csv', header=False, index=False)
validation_data.to_csv('validation.csv', header=False, index=False)

In [3]:
bucket = 'pa5-part2'
prefix = 'sagemaker/DEMO-xgboost-dm'
# Define IAM role
import boto3
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sagemaker
from sagemaker import get_execution_role
from sagemaker.predictor import csv_serializer


s3_input_train = boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(prefix, 'train/train.csv')).upload_file('train.csv')
s3_input_validation = boto3.Session().resource('s3').Bucket(bucket).Object(os.path.join(prefix, 'validation/validation.csv')).upload_file('validation.csv')

In [6]:
s3_input_train = sagemaker.s3_input(s3_data='s3://{}/{}/train'.format(bucket, prefix), content_type='csv')
s3_input_validation = sagemaker.s3_input(s3_data='s3://{}/{}/validation'.format(bucket, prefix), content_type='csv')


In [7]:
print(s3_input_train)

In [9]:
role = get_execution_role()

containers = {'us-west-2': '433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:latest',
              'us-east-1': '811284229777.dkr.ecr.us-east-1.amazonaws.com/xgboost:latest',
              'us-east-2': '825641698319.dkr.ecr.us-east-2.amazonaws.com/xgboost:latest',
              'eu-west-1': '685385470294.dkr.ecr.eu-west-1.amazonaws.com/xgboost:latest'}

sess = sagemaker.Session()

xgb = sagemaker.estimator.Estimator(containers[boto3.Session().region_name],
                                    role, 
                                    train_instance_count=1, 
                                    train_instance_type='ml.m4.xlarge',
                                    output_path='s3://{}/{}/output'.format(bucket, prefix),
                                    sagemaker_session=sess)
xgb.set_hyperparameters(eta=0.1,
                        objective='binary:logistic',
                        num_round=25)

xgb.fit({'train': s3_input_train, 'validation': s3_input_validation})

INFO:sagemaker:Creating training-job with name: xgboost-2019-04-11-02-28-47-705


2019-04-11 02:28:47 Starting - Starting the training job...
2019-04-11 02:28:48 Starting - Launching requested ML instances......
2019-04-11 02:29:55 Starting - Preparing the instances for training......
2019-04-11 02:31:16 Downloading - Downloading input data...
2019-04-11 02:31:46 Training - Training image download completed. Training in progress..
Arguments: train
[2019-04-11:02:31:47:INFO] Running standalone xgboost training.
[2019-04-11:02:31:47:INFO] File size need to be processed in the node: 2.32mb. Available memory size in the node: 8401.21mb
[2019-04-11:02:31:47:INFO] Determined delimiter of CSV input is ','
[02:31:47] S3DistributionType set as FullyReplicated
[02:31:47] 21000x23 matrix with 483000 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
[2019-04-11:02:31:47:INFO] Determined delimiter of CSV input is ','
[02:31:47] S3DistributionType set as FullyReplicated
[02:31:47] 6000x23 matrix with 138000 entries loaded from /opt/ml/input/data/v

In [10]:
xgb_predictor = xgb.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')


INFO:sagemaker:Creating model with name: xgboost-2019-04-11-02-33-28-142
INFO:sagemaker:Creating endpoint with name xgboost-2019-04-11-02-28-47-705


---------------------------------------------------------------------------!

In [12]:
xgb_predictor.content_type = 'text/csv'
xgb_predictor.serializer = csv_serializer
xgb_predictor.deserializer = None

dataset = pd.read_excel('default of credit card clients.xls')
dataset = dataset.drop('ID')
dataset = pd.concat([dataset['Y'], dataset.drop(['Y'], axis=1)], axis=1) 
train_data, validation_data, test_data = np.split(dataset.sample(frac=1, random_state=1729), [int(0.7 * len(dataset)), int(0.9 * len(dataset))])


def predict(data, rows=500):
    split_array = np.array_split(data, int(data.shape[0] / float(rows) + 1))
    predictions = ''
    for array in split_array:
        predictions = ','.join([predictions, xgb_predictor.predict(array).decode('utf-8')])

    return np.fromstring(predictions[1:], sep=',')

predictions = predict(test_data.as_matrix()[:, 1:])
predictions

array([0.59283876, 0.1414548 , 0.31579986, ..., 0.41416201, 0.11323805,
       0.11232713])

In [35]:
print(predictions.shape)
print(test_data.shape)
print(predictions)
print(np.round(predictions, 0).astype(int))
print(test_data['Y'].shape)
print(test_data['Y'])

(3000,)
(3000, 24)
[0.59283876 0.1414548  0.31579986 ... 0.41416201 0.11323805 0.11232713]
[1 0 0 ... 0 0 0]
(3000,)


In [41]:
predictions_rounded = np.round(predictions, 0).astype(int)
cm = pd.crosstab(index = test_data['Y'], columns= predictions_rounded, rownames=['Observed'], colnames=['Predicted'])
tn = float(cm.iloc[0,0]); fn = float(cm.iloc[1,0]); tp = float(cm.iloc[1,1]); fp = float(cm.iloc[0,1]); p = (tp+tn)/(tp+tn+fp+fn)*100
print("\n{0:<20}{1:<4.1f}%\n".format("Overall Classification Rate: ", p))
print("{0:<15}{1:<15}{2:>8}".format("Predicted", "No Default", "Default"))
print("Observed")
print("{0:<15}{1:<2.0f}% ({2:<}){3:>6.0f}% ({4:<})".format("No Default", tn/(tn+fn)*100,tn, fp/(tp+fp)*100, fp))
print("{0:<16}{1:<1.0f}% ({2:<}){3:>7.0f}% ({4:<}) \n".format("Default", fn/(tn+fn)*100,fn, tp/(tp+fp)*100, tp))


Overall Classification Rate: 82.2%

Predicted      No Default      Default
Observed
No Default     84% (2219.0)    33% (121.0)
Default         16% (414.0)     67% (246.0) 

